all:
	make blocks you
blocks:
	povray Output_Alpha= Display=false Width=644 Height=28 Antialias=true Output_File_Type=N blocks.pov
you:
	povray Output_Alpha= Display=false Width=28 Height=28 Antialias=true Output_File_Type=N you.pov
clean:
	rm *.png
