all:
	make 4dmaze you numbers
4dmaze:
	povray Output_Alpha= Display=false Width=644 Height=28 Antialias=true Output_File_Type=N 4dmaze.pov
you:
	povray Output_Alpha= Display=false Width=28 Height=28 Antialias=true Output_File_Type=N you.pov
numbers:
	povray Output_Alpha= Display=false Width=616 Height=56 Antialias=true Output_File_Type=N numbers.pov
clean:
	rm *.png
